title: IMiC Portal User Documentation
description: This page is a tutorial for using the IMiC Data Portal

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
